# Build worker image (VM template)
image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

init:

before_build:
  # Use GitVersion to determine build + version number from git tree
  - ps: gitversion /output buildserver
  - ps: Update-AppveyorBuild -Version "$env:GitVersion_NuGetVersion"
  - ps: nuget restore

build:
  # project: LogJam.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

test:
  assemblies:
    # only assemblies to test
    - 'test\**\*Tests.dll'

artifacts:
  - path: 'NuGetOut\*.nupkg'

cache:
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
