# Build worker image (VM template)
image: Visual Studio 2017

configuration: Release

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

init:

before_build:
  # Use GitVersion to determine build + version number from git tree
  - ps: gitversion /output buildserver
  - ps: Update-AppveyorBuild -Version "$env:GitVersion_NuGetVersion"
  - ps: nuget restore

build:
  # project: LogJam.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

test_script:
  - ps: .\test.ps1

#artifacts:
#  - path: 'NuGetOut\*.nupkg'

cache:
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
